# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/chen2021-web/android_kernel_huawei_hi6250
          kernel-dir: msm-4.9
          kernel-branch: phenix-1.0
          config: phenix_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 13
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
